# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setting_Dialog(object):
    def setupUi(self, setting_Dialog):
        setting_Dialog.setObjectName("setting_Dialog")
        setting_Dialog.resize(240, 118)
        self.gridLayout = QtWidgets.QGridLayout(setting_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(setting_Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.port_comboBox = QtWidgets.QComboBox(setting_Dialog)
        self.port_comboBox.setObjectName("port_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.port_comboBox)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(setting_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(setting_Dialog)
        self.buttonBox.accepted.connect(setting_Dialog.accept)
        self.buttonBox.rejected.connect(setting_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(setting_Dialog)

    def retranslateUi(self, setting_Dialog):
        _translate = QtCore.QCoreApplication.translate
        setting_Dialog.setWindowTitle(_translate("setting_Dialog", "设置"))
        self.label.setText(_translate("setting_Dialog", "port"))
